### PR TITLE
.

### PR DESCRIPTION
**Pull request by flyize**

### CODE REVIEW

**Comment by mkitchingh** [comment]
Hey @flyize and @davidkassa  Is this really a bunch of activity on the check-in app? I haven't used it for a few months since I haven't had a flight. Is this something new?

**Comment by davidkassa** [comment]
No new content. This is largely an upgrade to the latest version of ruby and rails to stay supported on Heroku.

**Comment by mkitchingh** [comment]
Thanks. @davidkassa  I didn't know there was anyone else out there doing any work with this. I gave up on Heroku last year, because it seemed Southwest had blocked that IP space. I'd start a new instance, and it would always get blocked after the first check-in. I've been running it on a local Ubuntu instance since then.  Are you aware of other users? Is there any sort of development discussion occurring anywhere?

**Comment by davidkassa** [comment]
Oh interesting. I haven't used it (as it's just my personal instance) in about a year.

**Comment by flyize** [comment]
Yeah, I'm working on getting a walkthrough created for Ubuntu 18.04 thanks to @davidkassa's updates.  It also appears that there was an API key update.  I'm testing the new key now.

**Comment by flyize** [comment]
Yay, it finally works with the new API key!

**Comment by mkitchingh** [comment]
There was one significant issue in Ubuntu that was missing from the old instructions. You and I discussed it here: https://github.com/flyize/southwest-checkin/commit/327357369a1eefff867914b9111059bd60fb28de#commitcomment-28026322 
starting on 3/13/18/. It has been working for me ever since. I could go to Heroku again, but it was failing (discussion earlier in the same thread).

**Comment by flyize** [comment]
So I think I've gotten all the documentation written up on how to start with a blank Ubuntu 18.04 server.  My only issue is that I need the following commit from @davidkassa added to my repo (and I have zero idea on how to do that, LOL). 
 https://github.com/davidkassa/southwest-checkin-3/commit/b8ad78a8713e2419114626682d31f9d320cf5aa7

Or maybe I should just create a pull request and have @davidkassa add the instructions to his repo.  He actually seems to know what he's doing and is probably a better keeper of the reins.

**Comment by mkitchingh** [comment]
So, I haven't updated anything in a long time. I just tried to add a new flight for next week, and it errors out. The error is below. There is a dot like a bullet point on the next line. This is a local Ubuntu setup. Any ideas? Anything I should try?
There was a problem retrieving your reservation. Please check the following fields to make sure they are correct:

**Comment by mkitchingh** [comment]
I also just tried this version https://github.com/davidkassa/southwest-checkin-3  
on a fresh heroku setup, and I get an error there too. Tried 2 different flights. 
There was a problem retrieving your reservation. Please check the following fields to make sure they are correct:
Payload can't be blank
User reservations is invalid

**Pull request merged**
